### ISSUE TITLE
implement calculation

### ISSUE THREAD

**Issue by yegor256** [yegor256/names-vs-complexity#1]
Let's make sure `make calc` works and produces real numbers for each Java class. Now it simply creates `1,1` CSV files for each class. We may see how Java parsing is implemented here https://github.com/yegor256/size-vs-immutability (see `calc.py)

**Comment by goonnors** [comment]
There are different opinions regarding the calculation of CC for binary operations || and &&, as well as for few fall through case statements
```
boolean c= a && b;
if ( c ) {  }
```
```
switch (x) {
case 1:
case 2:
	y = 1;
	break;
default:
	y = 2;
}
```
Can you specify a reliable source that I can focus on? Or a reliable tool for calculating metrics, like a checkstyle?

**Comment by yegor256** [comment]
@goonnors thanks for #2
